Repository AY2324S2-CS2113-W13-3/tp, pull requests merged in 2024-03, with the labels that each got.

#34 Fix gpa calculator
  src/main/java/gpa/GPACommand.java
  src/main/java/seedu/duke/CantVasMain.java
  src/main/java/seedu/duke/UI.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.High

#42 Added assertions for string length and file paths.
  src/main/java/seedu/duke/ExpenditureList.java
  src/main/java/storage/Storage.java
Labels: priority.Medium

#51 Bug fixes from week 9 tutorial
  src/main/java/seedu/duke/ExpenditureList.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#52 Enable assert in build.gradle
  build.gradle
Labels: type.Task

#53 Remove text-ui-test
  .github/workflows/gradle.yml
  src/main/java/motivationalquotes/MotivationalQuotes.java
  src/main/java/seedu/duke/CantVasMain.java
  src/main/java/seedu/duke/UI.java
Labels: type.Task

#70 Updated developer guide for features done in V1.0.
  docs/DeveloperGuide.md
  src/test/META-INF/MANIFEST.MF
Labels: severity.VeryLow

#69 Yan hui v2.0
  docs/DeveloperGuide.md
Labels: type.Task

#72 V2.0 test function - Graphic Calculator
  src/main/java/gc/gc.java
  src/main/java/seedu/duke/ProcessCommand.java
Labels: priority.Low

#83 Added one testing function in gc class
  src/main/java/gc/GC.java
Labels: priority.High, severity.High

#89 Add type to expenditure
  src/main/java/expenditure/Expenditure.java
  src/main/java/expenditure/ExpenditureList.java
  src/main/java/motivationalquote/MotivationalQuotes.java
  src/main/java/seedu/duke/ProcessCommand.java
  src/main/java/seedu/duke/UI.java
  src/main/java/storage/Storage.java
  src/test/java/expenditure/ExpenditureTest.java
  src/test/java/seedu/duke/MotivationalQuotesTest.java
  src/test/java/seedu/duke/UITest.java
Labels: type.Story, priority.Medium

#90 Yan hui v2.0
  src/main/java/expenditure/ExpenditureList.java
  src/main/java/seedu/duke/CantVasMain.java
  src/main/java/seedu/duke/ProcessCommand.java
  src/main/java/seedu/duke/UI.java
  src/main/java/storage/Storage.java
  src/main/java/timetable/Days.java
  src/main/java/timetable/TimetableList.java
  src/main/java/timetable/TimetableParser.java
  src/test/java/seedu/duke/ExpenditureListTest.java
  src/test/java/seedu/duke/UITest.java
Labels: type.Story, priority.High

#91 Add test cases
  src/main/java/expenditure/ExpenditureList.java
  src/main/java/seedu/duke/ProcessCommand.java
  src/main/java/seedu/duke/UI.java
  src/main/java/storage/Storage.java
  src/test/java/expenditure/ExpenditureListTest.java
  src/test/java/seedu/duke/CantVasMainTest.java
  src/test/java/seedu/duke/ExpenditureListTest.java
  src/test/java/storage/StorageTest.java
Labels: type.Task

#92 Add quick start to user guide
  docs/UserGuide.md
Labels: type.Task

#93 Yan hui v2.0
  src/main/java/expenditure/ExpenditureList.java
  src/main/java/seedu/duke/UI.java
  src/main/java/timetable/TimetableList.java
  src/main/java/timetable/TimetableParser.java
  src/test/java/expenditure/ExpenditureListTest.java
  src/test/java/seedu/duke/UITest.java
Labels: priority.Medium
