Repository AY2324S2-CS2113-W13-3/tp, pull requests merged in 2024-04, with the labels that each got.

#99 Change the way timetable is stored and added list by day
  src/main/java/seedu/duke/ProcessCommand.java
  src/main/java/seedu/duke/UI.java
  src/main/java/storage/Storage.java
  src/main/java/timetable/Days.java
  src/main/java/timetable/TimetableList.java
  src/main/java/timetable/TimetableParser.java
  src/test/java/seedu/duke/UITest.java
  src/test/java/storage/StorageTest.java
Labels: type.Story, priority.High

#104 Exception and Error handling for GPA and input scanner
  src/main/java/gpa/GPACommand.java
  src/main/java/seedu/duke/UI.java
  src/main/java/timetable/TimetableMain.java
Labels: priority.High, severity.High

#106 V2.0
  docs/UserGuide.md
Labels: type.Epic, type.Story, priority.High, severity.High

#114 Update manifest file
  META-INF/MANIFEST.MF
Labels: type.Bug

#176 fix timetable class bug
  src/main/java/timetable/TimetableList.java
Labels: type.Bug, severity.High

#181 Addressed Issue tracker #174, Command Summary is empty.
  docs/UserGuide.md
Labels: priority.Low

#182 Fixed issue #172: Input handling for adding expenses is not handled properly.
  src/main/java/expenditure/ExpenditureList.java
Labels: priority.High

#183 Fixed Issue #171. The formatting of features part of the user guide is not consistent.
  docs/UserGuide.md
Labels: severity.VeryLow

#184 Fixed issue #169 and issue #170.
  data/timetable.txt
  docs/UserGuide.md
Labels: severity.VeryLow

#185 Bug fix on GPA
  src/main/java/cantvasUI/UI.java
  src/main/java/exceptions/InvalidInputFormatException.java
  src/main/java/expenditure/ExpenditureList.java
  src/main/java/gpa/GPACommand.java
  src/main/java/processUserCommands/ProcessCommand.java
  src/main/java/processUserCommands/TimetableParser.java
  src/main/java/seedu/duke/CantVasMain.java
  src/main/java/timetable/TimetableList.java
  src/test/java/seedu/duke/CantVasMainTest.java
  src/test/java/seedu/duke/UITest.java
Labels: priority.High

#186 GPA deal with invalid cases
  src/main/java/gpa/GPACommand.java
  src/main/java/gpa/GPAMain.java
Labels: priority.Medium

#187 Fixed issue #168. Added clearer guide for using the timetable functions.
  docs/UserGuide.md
Labels: severity.Medium

#190 bugfix: delete class by class code instead of time
  src/main/java/timetable/TimetableList.java
Labels: severity.High

#191 Fixed issue #167. Added a message.
  src/main/java/timetable/TimetableList.java
Labels: severity.VeryLow

#194 fixed exception when user tries to delete with an invalid index
  src/main/java/CantvasUI/UI.java
  src/main/java/expenditure/ExpenditureList.java
Labels: severity.High

#195 Fixed issue #147. An error message will immediately appear when wrong GPA inputs are keyed in.
  data/timetable.txt
  docs/UserGuide.md
  src/main/java/CantvasUI/UI.java
  src/main/java/gpa/GPACommand.java
  src/main/java/gpa/GPAMain.java
Labels: priority.Medium

#196 Fixed issue #142. Added new descriptions in the UG to draw difference between the 2 different versions of adding expenditures.
  docs/UserGuide.md
Labels: priority.Medium

#197 make list expense display total expenses as 2dp
  data/timetable.txt
  src/main/java/expenditure/ExpenditureList.java
  src/test/java/expenditure/ExpenditureListTest.java
Labels: severity.VeryLow

#201 Refactor code
  docs/UserGuide.md
  docs/team/nyh3.md
  src/main/java/cantvasui/UI.java
  src/main/java/processusercommands/TimetableParser.java
  src/main/java/storage/Storage.java
  src/main/java/timetable/Days.java
  src/main/java/timetable/TimetableList.java
Labels: type.Enhancement

#202 Added J-unit test for timetable class.
  src/main/java/expenditure/ExpenditureList.java
  src/main/java/timetable/TimetableList.java
  src/test/java/expenditure/ExpenditureListTest.java
  src/test/java/timetable/TimetableTest.java
Labels: severity.Medium

#189 GPA bug fix for invalid input
  src/main/java/gpa/GPAMain.java
Labels: priority.High

#205 V2.1 GPA
  src/main/java/gpa/GPACommand.java
  src/main/java/gpa/GPAMain.java
  src/main/java/gpa/Module.java
  src/main/java/gpa/ModuleList.java
  src/test/java/seedu/duke/GPATest.java
Labels: priority.Medium

#207 Fixed issue #134. Standardised expenditure amount input to a maximum display of 2 decimal places.
  data/expenditure.txt
  src/main/java/expenditure/ExpenditureList.java
Labels: priority.Medium, severity.Medium

#212 Standardised outputs of view function where expenses amount are outputted in 2 decimal places.
  data/gpa.txt
  docs/team/Heart-of-N1.md
  src/main/java/expenditure/ExpenditureList.java
Labels: priority.Medium

#213 V2.1 GPA calculator update
  data/gpa.txt
  docs/UserGuide.md
  src/main/java/cantvasui/UI.java
  src/main/java/gpa/GPAMain.java
  src/main/java/gpa/ProcessListCommand.java
  src/main/java/processusercommands/ProcessCommand.java
  src/test/java/seedu/duke/GPATest.java
  src/test/java/seedu/duke/UITest.java
Labels: priority.High

#214 Updated Userguide for gpa calculator
  data/gpa.txt
  docs/UserGuide.md
  docs/illustration_gpalist.png
  docs/logo.png
Labels: priority.Medium

#215 V2.1 GC update (halfway)
  src/main/java/gc/ProcessGCCommand.java
  src/main/java/gc/YX.java
  src/main/java/gc/YlogX.java
  src/main/java/processusercommands/ProcessCommand.java
Labels: priority.Low

#217 Made the expenditure class more defensive.
  data/expenditure.txt
  data/gpa.txt
  docs/UserGuide.md
  src/main/java/cantvasui/UI.java
  src/main/java/expenditure/ExpenditureList.java
  src/test/java/expenditure/ExpenditureListTest.java
Labels: priority.Medium, severity.Medium

#220 Reorganize developer guide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/illustration_gpalist.png
  docs/images/img.png
  docs/images/img_1.png
  docs/images/logo.png
  docs/team/nyh3.md
Labels: type.Task

#233 V2.1 PPP update
  docs/team/HikoHikoHiko.md
Labels: priority.High

#292 fix potential bug if user forgets space between type and amt/
  src/main/java/expenditure/ExpenditureList.java
Labels: severity.Medium

#306 Hiko's workspace
  data/gpa.txt
  src/main/java/gpa/GPACommand.java
  src/main/java/gpa/ProcessListCommand.java
Labels: priority.High, severity.High

#308 Hiko's workspace
  src/main/java/gpa/ProcessListCommand.java
Labels: type.Bug, priority.Medium, severity.Medium
